# Generated by Django 5.0.7 on 2026-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_latitude',
            field=models.FloatField(blank=True, help_text="Officer's home-base latitude", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='base_longitude',
            field=models.FloatField(blank=True, help_text="Officer's home-base longitude", null=True),
        ),
    ]
