# Generated by Django 5.0.7 on 2026-09-01 09:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Main Hall', 'Entrance'", max_length=255)),
                ('camera_index', models.PositiveSmallIntegerField(default=0, help_text="OpenCV device index for the local-webcam demo (0 = the server's default/only webcam). Ignored once stream_url is set.")),
                ('stream_url', models.CharField(blank=True, help_text='RTSP/HLS URL for a real IP camera, once MediaMTX is set up. Leave blank to use camera_index (local webcam demo).', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='registry.institute')),
            ],
            options={
                'ordering': ['institute_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCamera',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Main Hall', 'Entrance'", max_length=255)),
                ('camera_index', models.PositiveSmallIntegerField(default=0, help_text="OpenCV device index for the local-webcam demo (0 = the server's default/only webcam). Ignored once stream_url is set.")),
                ('stream_url', models.CharField(blank=True, help_text='RTSP/HLS URL for a real IP camera, once MediaMTX is set up. Leave blank to use camera_index (local webcam demo).', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.institute')),
            ],
            options={
                'verbose_name': 'historical camera',
                'verbose_name_plural': 'historical cameras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
