# Generated by Django 5.0.7 on 2026-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcamera',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
