# Generated by Django 5.0.7 on 2026-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspectionassignment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionassignment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
