# Generated by Django 5.0.7 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_historicalinspectionassignment_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='distance_from_site_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalinspectionreport',
            name='is_geofence_verified',
            field=models.BooleanField(default=False, help_text='True when the submitted location is within the allowed site radius'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='distance_from_site_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='is_geofence_verified',
            field=models.BooleanField(default=False, help_text='True when the submitted location is within the allowed site radius'),
        ),
    ]
