# Generated by Django 5.0.7 on 2026-09-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('staff', 'institute', 'date')},
        ),
    ]
