# Generated by Django 5.0.7 on 2026-09-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='risksnapshot',
            new_name='analytics_r_institu_90ce62_idx',
            old_name='analytics_r_institu_1c9d0a_idx',
        ),
    ]
