# Generated by Django 5.0.7 on 2026-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_r_institu_1c9d0a_idx_analytics_r_institu_90ce62_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aialert',
            name='alert_type',
            field=models.CharField(choices=[('ATTENDANCE_MISMATCH', 'Attendance mismatch'), ('CCTV_OFFLINE', 'CCTV offline'), ('CCTV_OFFLINE_OVER_48H', 'CCTV offline over 48 hours'), ('FAILED_INSPECTION', 'Failed inspection'), ('UNUSUAL_ATTENDANCE', 'Unusual attendance pattern'), ('REPEATED_ISSUES', 'Repeated issues')], max_length=30),
        ),
    ]
