# Generated by Django 5.0.7 on 2026-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_aialert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aialert',
            name='surprise_inspection_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aialert',
            name='alert_type',
            field=models.CharField(choices=[('ATTENDANCE_MISMATCH', 'Attendance mismatch'), ('CCTV_OFFLINE', 'CCTV offline'), ('CCTV_OFFLINE_OVER_48H', 'CCTV offline over 48 hours'), ('FAILED_INSPECTION', 'Failed inspection'), ('UNUSUAL_ATTENDANCE', 'Unusual attendance pattern'), ('REPEATED_ISSUES', 'Repeated issues'), ('INSPECTION_GAP', 'Inspection gap'), ('HIGH_RISK', 'High overall risk')], max_length=30),
        ),
    ]
